---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: reactor-kubis-2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: pelabuhan.alterra.dev/i2p-2/react-i2p:149394736
        #image: ianisharpratama/react-i2p:v1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pelabuhan-i2p
